mod puzzle_part1;

use std::io::Error;

pub fn main() -> Result<(), Error> {
    puzzle_part1::main()?;

    Ok(())
}
